# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' hello function
#' @export
rcpp_hello <- function() {
    .Call(`_CASDr_rcpp_hello`)
}

#' geo dist
#'
#' @export
geo_dist <- function(lat1, lon1, lat2, lon2) {
    .Call(`_CASDr_geo_dist`, lat1, lon1, lat2, lon2)
}

#' ST_Dwithin: Geographic Distance
#'
#' Computes number of units within distance `cutoff` in meters from degree location measures.
#' @export
cppST_DWithin <- function(lat1, lon1, coord2, cut) {
    .Call(`_CASDr_cppST_DWithin`, lat1, lon1, coord2, cut)
}

#' cppST_Dist
#'
#' Computes distance in kilometers to a single point.
#' @export
cppST_Dist <- function(lat1, lon1, lat2, lon2) {
    .Call(`_CASDr_cppST_Dist`, lat1, lon1, lat2, lon2)
}

#' Distance calculator
#'
#' low level c++ function
#' @export
naive_dist <- function(lon1, lat1, lon2, lat2) {
    .Call(`_CASDr_naive_dist`, lon1, lat1, lon2, lat2)
}

